## ML ALgorithm

In [110]:
import pandas as pd

In [111]:
stats = pd.read_csv("player_mvp_stats.csv", index_col=0)

In [112]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45

In [113]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          59
3P            0
3PA           0
3P%        2086
2P            0
2PA           0
2P%         100
eFG%         59
FT            0
FTA           0
FT%         521
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W           605
L           605
W/L%        605
GB          605
PS/G        605
PA/G        605
SRS         605
dtype: int64

In [114]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]].head()

             Player  3PA
2    Elden Campbell  0.0
3     Irving Thomas  0.0
18       Jack Haley  0.0
20      Keith Owens  0.0
30  Benoit Benjamin  0.0

In [115]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]].head()

              Player  FTA
77        John Coker  0.0
92      Jason Sasser  0.0
103  Adrian Caldwell  0.0
119     Bruno Šundov  0.0
158   Jamal Robinson  0.0

In [116]:
stats = stats.fillna(0)

In [117]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [118]:
predictors = ["Age", "G", "GS", "MP", "FG", "FGA", 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS']

In [119]:
train = stats[~(stats["Year"] == 2022)]
test = stats[stats["Year"] == 2022]

In [120]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [121]:
reg.fit(train[predictors],train["Share"])

Ridge(alpha=0.1)

In [122]:
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [123]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [124]:
combination.sort_values("Share", ascending=False).head(20)

                 Player  Share  predictions
648        Aaron Gordon    0.0     0.099282
9744       Daniel Oturu    0.0     0.086680
9746      Fred VanVleet    0.0     0.117046
9747     Gary Trent Jr.    0.0     0.090201
9748        Isaac Bonga    0.0     0.088552
9749  Justin Champagnie    0.0     0.071313
9750         Khem Birch    0.0     0.059990
9751      Malachi Flynn    0.0     0.087684
9752         OG Anunoby    0.0     0.083589
9753      Pascal Siakam    0.0     0.156369
9754   Precious Achiuwa    0.0     0.075469
9755         Sam Dekker    0.0     0.108079
9756     Scottie Barnes    0.0     0.089415
9757     Svi Mykhailiuk    0.0     0.082326
9758     Thaddeus Young    0.0     0.090427
9759      Yuta Watanabe    0.0     0.091529
9775   Arnoldas Kulboka    0.0     0.097686
9745      David Johnson    0.0     0.103482
9743      Dalano Banton    0.0     0.078897
9777     Gordon Hayward    0.0     0.101299

In [125]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.009284513578234364

In [126]:
combination["Share"].value_counts()

0.0    605
Name: Share, dtype: int64

In [127]:
actual = combination.sort_values("Share", ascending=False)
predicted = combination.sort_values("predictions", ascending=False)
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [128]:
actual.merge(predicted, on="Player").head(5)

,Player,Share_x,predictions_x,Rk,Share_y,predictions_y,Predicted_Rk
0,Aaron Gordon,0.0,0.099282,1,0.0,0.099282,149
1,Daniel Oturu,0.0,0.086680,2,0.0,0.086680,300
2,Fred VanVleet,0.0,0.117046,3,0.0,0.117046,66
3,Gary Trent Jr.,0.0,0.090201,4,0.0,0.090201,239
4,Isaac Bonga,0.0,0.088552,5,0.0,0.088552,267

In [129]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)

In [130]:
ap = find_ap(combination)

In [131]:
ap

0.014554915054719592

In [132]:
years = list(range(1991,2023))

In [133]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [134]:
sum(aps) / len(aps)

0.6577005510471408

In [135]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    predictions["Diff"] = (predictions["Rk"] - predictions["Predicted_Rk"])
    return predictions

In [136]:
add_ranks(all_predictions[1])

                Player  Share  predictions  Predicted_Rk   Rk  Diff
1710       Karl Malone  0.857     0.192360             2    1    -1
10976   Michael Jordan  0.832     0.167672             3    2    -1
970         Grant Hill  0.327     0.128664             6    3    -3
4912      Tim Hardaway  0.207     0.059992            20    4   -16
8642         Glen Rice  0.117     0.033122            53    5   -48
...                ...    ...          ...           ...  ...   ...
10588   Horacio Llamas  0.000     0.010225           156  437   281
3768     Ennis Whatley  0.000     0.010287           155  438   283
11046  Kevin Salvadori  0.000     0.010594           154  439   285
1248    Aaron Williams  0.000     0.010608           153  440   287
7087     Melvin Booker  0.000    -0.055141           441  441     0

[441 rows x 6 columns]

In [137]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [138]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [139]:
mean_ap

0.7039225104781103

In [140]:
all_predictions[all_predictions["Rk"] < 5].sort_values("Diff").head(10)

                        Player  Share  predictions  Predicted_Rk  Rk  Diff
3718               Cam Reddish  0.000     0.079939           402   4  -398
11819  Timothé Luwawu-Cabarrot  0.000     0.079968           401   3  -398
8592          Keita Bates-Diop  0.000     0.080062           399   2  -397
10349              Sam Merrill  0.000    -0.006853           370   3  -367
8572             Jae'Sean Tate  0.000    -0.006815           369   4  -365
10332             Axel Toupane  0.000    -0.005687           356   2  -354
1334                Jason Kidd  0.712     0.027957            52   2   -50
5420                Steve Nash  0.839     0.032686            47   1   -46
8910           Peja Stojaković  0.228     0.035581            39   4   -35
5438                Steve Nash  0.739     0.051338            35   1   -34

In [141]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.091689  eFG%
18  0.032726   DRB
17  0.020950   ORB
10  0.016064    2P
21  0.012520   STL
15  0.011733   FTA
22  0.011142   BLK
28  0.008351  W/L%
12  0.007431   2P%
20  0.006651   AST
5   0.005462   FGA
25  0.004975   PTS
4   0.004482    FG
7   0.004453    3P
0   0.000329   Age
29  0.000317    GB
26  0.000298     W
1   0.000095     G
2   0.000010    GS
31 -0.000239  PA/G
27 -0.000388     L
32 -0.000516   SRS
30 -0.000585  PS/G
24 -0.002625    PF
3  -0.003867    MP
16 -0.004179   FT%
14 -0.006301    FT
23 -0.008825   TOV
9  -0.010093   3P%
8  -0.010236   3PA
11 -0.015632   2PA
19 -0.026384   TRB
6  -0.156359   FG%

In [142]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [143]:
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [144]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [145]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [146]:
mean_ap

0.709625030031863

In [147]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [148]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors + ["NPos", "NTm"])

In [149]:
mean_ap

0.7637288073123987

In [150]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [151]:
mean_ap

0.7215121024486348

In [152]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [153]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year].copy()
        test = stats[stats["Year"] == year].copy()
        sc.fit(train[predictors])
        train[predictors] = sc.transform(train[predictors])
        test[predictors] = sc.transform(test[predictors])
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [154]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [155]:
mean_ap

0.7215121024486348

In [156]:
sc.transform(stats[predictors])

array([[ 0.05879521,  1.17143997, -0.15913318, ..., -0.05602537,
        -0.27881836, -0.38532304],
       [ 0.53022738,  1.17143997,  1.93933415, ...,  0.93341356,
        -0.27881836,  2.80498604],
       [-1.11978522, -0.02372751, -0.88155636, ..., -1.04546431,
         0.48793213, -0.78411168],
       ...,
       [-0.41263697,  0.05595033, -0.46874311, ...,  0.17215205,
         1.32109925, -0.37577707],
       [-1.82693348,  0.17546707,  0.28808117, ..., -0.98027076,
         0.23360901, -0.27369342],
       [-0.41263697,  1.09176214,  1.87053194, ...,  0.17215205,
        -0.41888513,  1.05339407]])

In [160]:
predictions=all_predictions.drop_duplicates(subset = "Player")

In [164]:
MVPS=predictions[predictions["Predicted_Rk"]<6].sort_values("Predicted_Rk")
MVPS

                      Player  Share  predictions  Predicted_Rk   Rk  Diff
11978  Giannis Antetokounmpo  0.932     0.203543             1    1     0
10065           James Harden  0.768     0.189648             2    2     0
3890            LeBron James  0.001     0.168694             3   11     8
5722             Joel Embiid  0.049     0.150686             4    7     3
7285           Anthony Davis  0.000     0.139145             5  367   362